spring:
  application:
    name: omop-converter-prod
  main:
    allow-bean-definition-overriding: true

internal:
  kafka:
    bootstrap.servers: 127.0.0.1:9093
    topic: topic
  tracking:
    enabled: false
  omop:
    db:
      url: jdbc:sqlserver://10.85.9.161:1433;database=omop;
      username: omopuser
      password: d1fguaHa
      schema: omopv5
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
